name: "功能请求 / Feature Request"
description: "提出新功能或改进建议"
title: "[Feature]: "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢你的想法！请补充以下内容，帮助我们评估与设计。

  - type: textarea
    id: problem
    attributes:
      label: 相关问题 / Problem
      description: 此功能要解决的痛点或场景
      placeholder: 例如：侧边栏过窄时按钮拥挤，期望…
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 方案构想 / Proposal
      description: 你期望的行为、交互与大致方案
      placeholder: 例如：在超窄宽度下仅显示图标按钮，悬停显示提示…
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 / Alternatives
      description: 你考虑过的其它方案（若有）

  - type: textarea
    id: context
    attributes:
      label: 附加上下文 / Additional Context
      description: 设计稿、截图、链接等

